language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
    secure: ntuAWsMBeMSArHDeImkNsgOd9ZPo231kmAaI3Sglg4RZ/ARWyblc5koTifxP4ZZ27+sxR6+1EJl1i85RbVYcrVkEblgPPMXrmCosV0VppH4XbeW9pQ5iqkhpAsu0lN8XX1+YkZjcWW3LUtVydDFAq1lgwLIHkMqUGcIiDzEWy+g1PrjTDNy2DBOiKo8rZV78/5M3FC43vFqeIlKRo4PXUifu052Hl5nrypyaZZq/6HNCGuVvuB3j5QJvf0CctjpPNraObEUQTQoZVGoIf0HsW1l68Qoc7zqsipVGdGtD3rGkSxKVhh0+SdWrgHg2oRzqPdej6LKF6DhQ7FiacSruN2AfAZLe+Ct6K+lBmbeqCvToOYzMcZrxse0IwdE+WW14rn1sf/vXPbE/BhyZyASXy21tjjyNg0rIiQ0fpHOKPm6cy59ZkjtJctREJFIL5FoIFYe9TH0WhTZhD+P6aLpCVn1jF3TLO7UKdquAuuXa1TlbnMrMv5uR4uRGNdzLYdOvoJOEuVgicr5Ra03Rw24buihMRbHo3XV77taG1JCJ7bPfz58H4nEEyD+iADME9GlUC5yfGC8iddO47nrG6Hin3ivgxpkuIfZ1QzDQ3IOBgmdo+VN3U+Yd6fFfD3/3sPzOSMUouO5oGJ93RzNGo4ZsBPcEKkMbhgEqdRopk/gUT18=
  glob:
    secure: sDb+xiJZ+fCAEdhMZrRk6elNuhWmOWGzgHhY089NiC/g45nMYR4TJFkYuhPD1rA+GMi8KRSK5+D8v2i/1MFUx0nWBqUYQhpzSDkGDhMmLQZkMrsr563z6tmLKI/Yia9RvEuOP5wom06pv10Jl2faBGT3YUuEBdfX/Y8JJvDiW3fi4UNtIEu82ZVAjr7zdkJJ5ixiyYG0SR91wgTlEzhw+dtxZLuUwZ+AjsyXmfb1k0Q0BkqH7UiMsxj1Fhp+YU+aDWp1SpWIFU1H528FSt3xEAF5kHbuh0kiAAxYd3kRj6UeP3dy19uDhYbATHIiFaLnUftwqq5B9nF5rJAkqwyVeAC0wvNJRyt87tdK5UW7g1toTbECYRrq5pG4xp6BP52IS05VRwDR2Q1Ty3FTZaVQqTB1JKx4zi0Bdh9KTDtMJ+xpZiNX7z8Awj5LJPwc6Imt/wvl4aIPzufyegN7YKNq7nGv/nYwH7yZ9tUbZ6yaIPCRaQIFAbenYE/CoiU3fusWB+aCea9X2ldagebW1oTjLa9rcDxorUYegSuCbvx38ZD7zEk14Zhw60R+hD0VSMlZFcRBzwbGzLVkcNIxBWqd8ChMfluN0kvVzbyVggPcmfYTS25NJOH48swEwNgBHDgo8XrynLF4oQLgXDXe8scFCGdFFwrUc0ZriE/lj+NhjVY=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
